//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnet_vj_12_xaml_app.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klub", Namespace="http://schemas.datacontract.org/2004/07/dnet_vj_12")]
    [System.SerializableAttribute()]
    public partial class Klub : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GodinaOsnivanjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SportField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GodinaOsnivanja {
            get {
                return this.GodinaOsnivanjaField;
            }
            set {
                if ((this.GodinaOsnivanjaField.Equals(value) != true)) {
                    this.GodinaOsnivanjaField = value;
                    this.RaisePropertyChanged("GodinaOsnivanja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sport {
            get {
                return this.SportField;
            }
            set {
                if ((object.ReferenceEquals(this.SportField, value) != true)) {
                    this.SportField = value;
                    this.RaisePropertyChanged("Sport");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DajKlub", ReplyAction="http://tempuri.org/IService1/DajKlubResponse")]
        dnet_vj_12_xaml_app.ServiceReference1.Klub DajKlub(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DajKlub", ReplyAction="http://tempuri.org/IService1/DajKlubResponse")]
        System.Threading.Tasks.Task<dnet_vj_12_xaml_app.ServiceReference1.Klub> DajKlubAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DajSveKlubove", ReplyAction="http://tempuri.org/IService1/DajSveKluboveResponse")]
        dnet_vj_12_xaml_app.ServiceReference1.Klub[] DajSveKlubove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DajSveKlubove", ReplyAction="http://tempuri.org/IService1/DajSveKluboveResponse")]
        System.Threading.Tasks.Task<dnet_vj_12_xaml_app.ServiceReference1.Klub[]> DajSveKluboveAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : dnet_vj_12_xaml_app.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<dnet_vj_12_xaml_app.ServiceReference1.IService1>, dnet_vj_12_xaml_app.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public dnet_vj_12_xaml_app.ServiceReference1.Klub DajKlub(string id) {
            return base.Channel.DajKlub(id);
        }
        
        public System.Threading.Tasks.Task<dnet_vj_12_xaml_app.ServiceReference1.Klub> DajKlubAsync(string id) {
            return base.Channel.DajKlubAsync(id);
        }
        
        public dnet_vj_12_xaml_app.ServiceReference1.Klub[] DajSveKlubove() {
            return base.Channel.DajSveKlubove();
        }
        
        public System.Threading.Tasks.Task<dnet_vj_12_xaml_app.ServiceReference1.Klub[]> DajSveKluboveAsync() {
            return base.Channel.DajSveKluboveAsync();
        }
    }
}
